# Generated by Django 6.0.7 on 2026-08-16 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('payment_method', models.CharField(choices=[('UPI_GPAY', 'Google Pay UPI'), ('UPI_PHONEPE', 'PhonePe UPI'), ('UPI_PAYTM', 'Paytm UPI'), ('UPI_GENERIC', 'Generic UPI (BHIM/ID)'), ('CREDIT_CARD', 'Credit / Debit Card (RuPay/Visa/Mastercard)'), ('NET_BANKING', 'Net Banking (HDFC/SBI/ICICI/Axis)')], default='UPI_PHONEPE', max_length=30)),
                ('payment_status', models.CharField(choices=[('SUCCESS', 'Payment Completed'), ('FAILED', 'Payment Failed'), ('PENDING', 'Payment In-Progress')], default='SUCCESS', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('upi_vpa', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
        ),
    ]
