# Generated by Django 6.0.7 on 2026-08-16 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_alter_movie_options_movie_backdrop_movie_cast_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=50)),
                ('screen_type', models.CharField(choices=[('IMAX 3D', 'IMAX with Laser 3D'), ('Dolby Atmos 4K', 'Dolby Atmos 4K Laser'), ('4DX', '4DX Motion Experience'), ('ICE Immersive', 'ICE Immersive Experience'), ('Gold Class / INSIGNIA', 'INSIGNIA Luxury Lounge'), ('Standard 2D', 'Standard Digital 2D')], default='Dolby Atmos 4K', max_length=50)),
                ('total_rows', models.IntegerField(default=8)),
                ('total_cols', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(choices=[('PVR INOX', 'PVR INOX Multiplex'), ('Cinepolis', 'Cinépolis VIP'), ('MovieMax', 'MovieMax Cinemas'), ('Miraj', 'Miraj Cinemas'), ('Carnival', 'Carnival Cinemas')], default='PVR INOX', max_length=50)),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi-NCR', 'Delhi-NCR'), ('Bengaluru', 'Bengaluru'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Pune', 'Pune'), ('Ahmedabad', 'Ahmedabad'), ('Jaipur', 'Jaipur'), ('Chandigarh', 'Chandigarh')], default='Mumbai', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('facilities', models.CharField(default='Dolby Atmos 7.1, 4K Laser, In-Seat Dining, Recliners', max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('language', models.CharField(default='Hindi', max_length=50)),
                ('format', models.CharField(default='Dolby Atmos 4K', max_length=50)),
                ('silver_price', models.DecimalField(decimal_places=2, default=220.0, max_digits=6)),
                ('gold_price', models.DecimalField(decimal_places=2, default=380.0, max_digits=6)),
                ('recliner_price', models.DecimalField(decimal_places=2, default=650.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='theaters.screen')),
            ],
            options={
                'ordering': ['show_date', 'show_time'],
            },
        ),
        migrations.AddField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theaters.theater'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_label', models.CharField(max_length=5)),
                ('seat_number', models.IntegerField()),
                ('seat_type', models.CharField(choices=[('SILVER', 'Silver Class (Front Rows)'), ('GOLD', 'Gold Prime (Center Executive)'), ('RECLINER', 'Royal Recliner (VIP Lounge)')], default='GOLD', max_length=20)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theaters.screen')),
            ],
            options={
                'ordering': ['row_label', 'seat_number'],
                'unique_together': {('screen', 'row_label', 'seat_number')},
            },
        ),
    ]
