# Generated by Django 6.0.7 on 2026-08-16 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('COMBO', 'Bollywood Blockbuster Combos'), ('SNACKS', 'Desi Snacks & Samosas'), ('BEVERAGES', 'Chai & Beverages'), ('POPCORN', 'Gourmet Popcorn'), ('DESSERT', 'Desi Sweet Treats')], default='COMBO', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('booking_status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('CONFIRMED', 'Booking Confirmed'), ('CANCELLED', 'Booking Cancelled')], default='CONFIRMED', max_length=20)),
                ('ticket_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('snack_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=45.0, max_digits=6)),
                ('gst', models.DecimalField(decimal_places=2, default=38.0, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('qr_code_data', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='theaters.showtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSnack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snacks', to='bookings.booking')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.snackitem')),
            ],
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_history', to='theaters.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats_all', to='theaters.showtime')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='bookings.booking')),
            ],
            options={
                'unique_together': {('showtime', 'seat')},
            },
        ),
    ]
