# Generated by Django 6.0.7 on 2026-08-16 00:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-rating', '-created_at']},
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default='Superstar Ensemble', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='certification',
            field=models.CharField(choices=[('U', 'Universal (U)'), ('U/A', 'Parental Guidance (U/A)'), ('A', 'Adults Only (A)'), ('S', 'Special Class (S)')], default='U/A', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Bollywood Legend', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_bollywood_hit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_now_showing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi (Bollywood)'), ('Telugu', 'Telugu (Tollywood)'), ('Tamil', 'Tamil (Kollywood)'), ('Malayalam', 'Malayalam (Mollywood)'), ('Kannada', 'Kannada (Sandalwood)'), ('Punjabi', 'Punjabi'), ('English', 'English (Hollywood Dubbed)')], default='Hindi', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='music_director',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tomatometer',
            field=models.IntegerField(default=90, help_text='Audience Score percentage'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=150, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=8.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
