# Generated by Django 6.0.7 on 2026-08-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options_movie_backdrop_movie_cast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='theme_tags',
            field=models.CharField(blank=True, help_text='Themes e.g. education, upsc, student, crime, horror', max_length=255, null=True),
        ),
    ]
